import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner.js";
import Nav from "../components/Nav.js";
// import styles from "../styles/Home.module.css";

export default function Home() {
  const styles = {
    image: "position:absolute; top:0; left:0; width:100%; height:100%; object-fit:cover; position:right-[20%] z-index-1",
    imageWrapper:"relative w-full ",
}

  const handleOnBannerBtnClick = () => {
    buttonText = "Java Store";
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.imageWrapper}>
        <Nav/>
      <Image
        className={styles.image}
        // look into putting a loader here as the image takes a while to load
        src="/static/Banner.png"
        alt="logo with coffee finder text"
        width={2000}
        height={500}
        />
      </div>
      <main>
        <Banner buttonText="Java!!" handleOnClick={handleOnBannerBtnClick} />
      </main>

      <footer></footer>
    </div>
  );
}
