import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner.js";
import Nav from "../components/Nav.js";
import Footer from "../components/Footer.js";
import Card from "../components/Card.js";
// imported the dummy data for coffee stores and products
import CoffeeStores from "../data/coffee-stores.json";
// import CoffeeProducts from "../data/coffee-products.json";

export default function Home() {
  const styles = {
    image:
      "position:absolute; top:0; left:0; width:100%; height:100%; object-fit:cover; position:right-[20%] z-index-1",
    imageWrapper: "relative w-full ",
    cardLayout:
      "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 align-middle justify-items-center",
  };
  const handleOnBannerBtnClick = () => {
    buttonTextStores;
    buttonTextProducts;
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder App in NextJS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.imageWrapper}>
        <Nav />
        <Image
          className={styles.image}
          src="/static/Banner.png"
          alt="logo with coffee finder text"
          width={2000}
          height={500}
        />
      </div>
      <main>
        <Banner
          buttonTextStores=<h1>
            Java <span className="hover:text-[#FACC15]">Joints</span>
          </h1>
          buttonTextProducts=<h1>
            Java <span className="hover:text-[#FACC15]">Juices</span>
          </h1>
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.cardLayout}>
          {CoffeeStores.map((CoffeeStores) => {
            return (
              <Card
                key={CoffeeStores.id}
                name={CoffeeStores.name}
                url={CoffeeStores.imgUrl}
                href={`/coffee-stores/${CoffeeStores.id}`}
                text="Find a coffee store near you and get your java fix"
              />
            );
          })}
        </div>
      </main>
      <footer
        className="
             inset-x-0
             bottom-0"
      >
        <Footer />
      </footer>
    </div>
  );
}
